name: Run tests

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Set env
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Run tests
        run: yarn test --coverage --silent

      - name: Build
        run: yarn build

      - name: Publish
        run: >-
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLSH_KEY }}' >> .npmrc
          npm publish --access=public
